repo: 'dog-rescue-pattern-library'

naming: true
restrictFileTypes: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

allFiles:
  html:
    valid: true
    bestPractices: true
  css:
    valid: true
    bestPractices: true
  md:
    valid: true
